#!/bin/sh
#
# Load cryptodev kernel module for hardware crypto acceleration
#
#declare DAEMON in line with the buildroot manual’s SNNfoo start script template (though one shot script)
DAEMON="cryptodev"

case "$1" in
	start)
		printf "Loading cryptodev module: "
		modprobe $DAEMON
		if [ -e /dev/crypto ]; then
			echo "OK"
		else
			echo "FAIL"
		fi
	;;
	stop)
		printf "Unloading cryptodev module: "
		rmmod $DAEMON 2>/dev/null
		echo "OK"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
