#!/bin/sh
# Demo script to show down hooks are working
# This runs before the interface is brought down

LOGFILE="/var/log/network-down.log"

echo "$(date): DOWN script triggered for interface $IFACE" >> $LOGFILE
echo "  Logical interface: $IFACE" >> $LOGFILE
echo "  Address family: $ADDRFAM" >> $LOGFILE
echo "  Method: $METHOD" >> $LOGFILE

exit 0
