#!/bin/sh
# Demo script to show pre-up hooks are working
# This runs before the interface is brought up

LOGFILE="/var/log/network-preup.log"

echo "$(date): PRE-UP script triggered for interface $IFACE" >> $LOGFILE
echo "  Logical interface: $IFACE" >> $LOGFILE
echo "  Address family: $ADDRFAM" >> $LOGFILE
echo "  Method: $METHOD" >> $LOGFILE

exit 0
