#! /bin/sh
#
# bank-admin
#
# first Version:           2014-09-23  sebastien.matz@eurogiciel.fr
#

BANK1_ROOTFS="/dev/mtdblock2"
BANK2_ROOTFS="/dev/mtdblock5"

# "fw_printenv bank1_status" displays "bank1_status=confirmed" or "bank1_status=blank", so "eval bank1_status=confirmed" actually sets bank1_status to "confirmed" in this script
eval $(fw_printenv bank1_status)
eval $(fw_printenv bank2_status)

usage="0"
if [ "$1Z" = "-hZ" ]; then
    usage="1"
fi
if [ "$1Z" = "--helpZ" ]; then
    usage="1"
fi
if [ "$usage" = "1" ]; then
    echo "Usage: $0"
    echo "   or: $0 --confirm"
    echo
    echo "Display which bank is currently booted. "
    echo "With option --confirm, the current bank is confirmed and U-Boot variables updated. "
    echo
    exit 0
fi

root_part="$(sed -n 's|.*'root'=\([^ ]\+\).*|\1|p' < /proc/cmdline)"
bank="0"
echo "Root filesystem is '$root_part', bank1_status is '$bank1_status' and bank2_status is '$bank2_status'"
if [ $root_part = $BANK1_ROOTFS ]; then
    if [ "x"$bank1_status = "xbooted" ]; then
    echo " => bank #1"
    bank="1"
    fi

    if [ "x"$bank1_status = "xconfirmed" ]; then
    echo " => bank #1"
    bank="1"
    fi
fi

if [ $root_part = $BANK2_ROOTFS ]; then
    if [ "x"$bank2_status = "xbooted" ]; then
    echo " => bank #2"
    bank="2"
    fi

    if [ "x"$bank2_status = "xconfirmed" ]; then
    echo " => bank #2"
    bank="2"
    fi
fi

if [ $bank = "0" ]; then
    echo " => cannot guess current bank"
fi
echo

if [ "x$1" = "x--confirm" ]; then
    echo "Update U-Boot environment"
    if [ $bank = "1" ]; then
    fw_setenv bank1_status "confirmed" && fw_setenv bank2_status "blank" && echo " => bank #1 confirmed"
    echo
    exit 0
    
    elif [ $bank = "2" ]; then
    fw_setenv bank1_status "blank" && fw_setenv bank2_status "confirmed" && echo " => bank #2 confirmed"
    echo
    exit 0

    else
    echo " => Error"
    echo
    exit 1
    fi
fi
